---
driver:
  name: ec2
  ENV['AWS_ACCESS_KEY_ID']: "<%= ENV['AWS_ACCESS_KEY_ID']%>"
  ENV['AWS_SECRET_ACCESS_KEY']: "<%= ENV['AWS_SECRET_ACCESS_KEY']%>"
  transport.ssh_key: ~/WebServer.pem
  region: us-west-2
  availability_zone: a
  require_chef_omnibus: true


transport:
    ssh_key: ~/WebServer.pem

provisioner:
  name: chef_solo

platforms:
  - name: redhat 
    driver:
        image_id: ami-775e4f16

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
